# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/multichoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class MultiChoiceDialog(QDialog):
    def setupUi(self, Dialog, options, title="Dialog", size=(322, 280)):
        self.Dialog = Dialog

        self.Dialog.setObjectName(title)
        self.Dialog.setFixedSize(*size)

        self.options = options
        self.size = size

        self.scrollArea = QtWidgets.QScrollArea(self.Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(5, 5, size[0] - 10, size[1] - 10))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 279, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")

        self.radioButtons = []
        for idx, option in enumerate(self.options):
            self.radioButtons.append(
                QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
            )
            self.radioButtons[-1].setObjectName(str(self.options[0]))
            self.gridLayout.addWidget(self.radioButtons[-1], idx, 0, 1, 1)

        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.return_value)
        self.gridLayout.addWidget(self.pushButton, len(self.options), 1, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog, title=title)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, title=""):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", title))
        for idx, option in enumerate(self.options):
            option = str(option)
            self.radioButtons[idx].setText(_translate("Dialog", option))
        self.pushButton.setText(_translate("Dialog", "OK"))

    def return_value(self):
        self.result = None
        for idx, button in enumerate(self.radioButtons):
            if button.isChecked():
                print(idx)
                self.result = idx
                self.Dialog.close()
                break


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = MultiChoiceDialog()
    ui.setupUi(Dialog, options=['testlongerstring1', 'test2', 'test3', 'test4'])
    Dialog.show()
    app.exec_()
    print(ui.result)
